### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by axhlzy** [xhawk18/s_task#9]
针对 ` void s_task_create(void* stack, size_t stack_size, s_task_fn_t task_entry, void* task_arg) ` 提出的小建议

可以把 前两个参数稍微封装一下，抽象成 TaskID （实际上就是一个创建的栈指针），大小不用一次性初始化写死，也可以借鉴 java ArrayList 的动态大小分配动态扩容 stack，至于扩容操作可能导致栈指针的变化

```
可以使用二级指针来解决问题
typedef void** Task；

或者是：
typedef struct
{
    int ID;
    void* statck;
    size_t stack_size;
} TaskID;

再或者使用 map<int,void*> TaskID
```

看起来简洁一些，让暴露出来的API变成

`void s_task_create(TaskID* taskID, s_task_fn_t task_entry, void* task_arg)`

后面的 join 等api 对应使用过方式也都由 taskid 接管

**Comment by xhawk18** [comment]
建议是不错，但是实际效果会有问题。栈扩容后，指向栈里内容的指针就废了，程序出bug几乎是必然的。

第二个为什么没设计成id的方式，因为最开始的设计目的，为两个嵌入式小芯片提供多任务支持（内存 < 32k）。
为了系统的稳定性，不引入任何动态内存分配和c++的元素。
实测应用于一个uwb测量程序，实测结果令人非常满意，响应速度和内存需求均比抢占式os好。

实际上如果能动态管理stack（或预开一个足够大的 stack），直接返回一个handle就可以了。但是做不到啊。。。
```
int s_task_create(s_task_fn_t task_entry, void* task_arg);
```

**Comment by axhlzy** [comment]
哈哈 大佬说的有道理  恕小弟考虑不周了  ~
